# MYSQL db creating
version: '3'  
services:
  mydbos:
    image: mysql:5.7
    volumes:
	- mysql_storage:/var/lib/mysql
    restart: always
    environment:
	MYSQL_ROOT_PASSWORD: rootpass
	MYSQL_USER:vishal
	MYSQL_PASSWORD:123
	MYSQL_DATABASE: mydb

volumes:
    mysql_storage		
    